// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebsmnftlbmrjtvmhflti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVic21uZnRsYm1yanR2bWhmbHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjU2MjUsImV4cCI6MjA1OTk0MTYyNX0.W9t24BpstgITrxKk-ZahZBjm3pnf8KTJXt-jfCQ_VwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);